version: '2.4'

networks:
  dataservicedevelopmentkit_default:
    name: dataservicedevelopmentkit_default
  proxy-redirect:
    name: proxy-redirect

volumes:
  db-edge-apps-dataservicedevelopmentkit-volume:
  db-edge-apps-simulation-volume:


services:
  # MQTT Broker
  ie-databus:
    image: eclipse-mosquitto:1.6.10
    networks:
      - dataservicedevelopmentkit_default
    ports:
      - 11883:1883
    mem_limit: 128mb
    restart: unless-stopped

  # Services
  edgeappdataservice:
    image: siemensindustrialedge/dataservicedevelopmentkit:2.1.0
    environment:
      - EXTENDED_ERRORS=true
      - LOG_DEBUG_INFO=true
    ports:
      - 4203:4203
    networks:
      - dataservicedevelopmentkit_default
      - proxy-redirect
    volumes:
      - '/tmp/siemens/automation:/tmp/siemens/automation'
      - type: volume
        source: db-edge-apps-dataservicedevelopmentkit-volume
        target: /home/edge/filedb
    mem_limit: 128mb
    restart: unless-stopped

  simulation:
    image: siemensindustrialedge/dataservicesimulation:1.5.3
    environment:
      - PLATFORM=edge
      - OPERATOR_PLAN=edge
      - DBSERVICETYPE=postgres
      - DBSERVICE=Edge
      - EXTENDED_ERRORS=true
      - LOG_DEBUG_INFO=true
      - MQTT_BROKER_URL=tcp://ie-databus:1883
      - MQTT_BROKER_USR=
      - MQTT_BROKER_PSW=
      - SIM_MODE=MQTT
      - AUTHENTICATION_MODE=sim-edge
      - APPLICATION_NAME=edgeappdataservice
      - POSTGRES_DB_FILE=/run/postgres-db
      - POSTGRES_USER_FILE=/run/postgres-user
      - POSTGRES_PASSWORD_FILE=/run/postgres-passwd
      - START_POSTGRES=1
      - POSTGRES_START_ARGS=-B 1MB
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - 4519:4519
    networks:
      - dataservicedevelopmentkit_default
      - proxy-redirect
    mem_limit: 128mb
    volumes:
      - '/tmp/siemens/automation:/tmp/siemens/automation'
      - type: volume
        source: db-edge-apps-simulation-volume
        target: /var/lib/postgresql/data
    restart: unless-stopped
